sudo: false
dist: trusty
language: node_js
node_js: "7"
cache: yarn
env:
  # Cut down the installation stuff. Always target Production.
  - ASSET_PUBLIC_PATH="//components.becauseofhope.org/" NODE_ENV=production
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: AKIAJBWWL5AXTGQI6OQQ
  secret_access_key:
    secure: "pSOFbo+CoTYuc7pku6wmlJnE84u3mVi5myKZTyME+mP3QDd/rgjBmym36/o0QyMr4ZEYYUUiLQ/X73bM26O1hjJC7anZ+kWzRK15QJzshZk10JH2X227PQY+OTAZAGc9gBI1TBptaj2m1XmWw+8xPMHmgV9tiDkPjTB281NvZEAAT+hFE6uKvLpw1nntt6aivsBZ9o8HIWzGWfQhnjg4UxPrDZUzf31W+JmBkuq+QFaoF5/q7qwoxdFk1s9DiymGiSaWnXaQ2x2FzNOsO/B+3yyER8y3MX10gCuUbFtCy3yKby8mHUwrH/u+fVyvTb0FQqRNpGYeZcWknRgokI4POh8tQpmgIBgXXxWzpag3Px7tapGpCuD5sVKndwowNCc9BDkusKqtaikJEUC0uqxYvFMxCbEM1UKuc4brikywHwnSnTfvrnkWWEmTbcYgVGz64P7GEMkq9BMluQLcY4RNFrjypXD1gb3prpZnsPWbxZCVijBgKXTTSd9n5lApFTln+zjExNmEfPjom/tz4Q+RsRxRlQuCE2Ivu15KSnp9c2IvQ+d5ggqQpd6MzHvAY49RGjikHCjdXfYCmNKLeZLZL+VIo8OomEhJvh0m1RAFvYWkEc1EF2UedVeYfHwKHIxoiYddILDiWwMxvmIvrw81liC1MDKCV+IB8Gp+Fg+cN4c="
  bucket: components.becauseofhope.org
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    branch: master
    repo: becauseofhope/boh_components
